services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: mux-demo-app:latest
    restart: unless-stopped
    environment:
      - NEW_RELIC_OTLP_ENDPOINT=otlp.nr-data.net:4317
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.27-bookworm-otel
    restart: unless-stopped
    ports:
      - "${PUBLIC_PORT:-8080}:80"
    depends_on:
      app:
        condition: service_started
    environment:
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - type: bind
        source: ${PWD}/nginx/nginx.conf.template
        target: /etc/nginx/nginx.conf.template
      - type: bind
        source: ${PWD}/nginx/docker-entrypoint.sh
        target: /docker-entrypoint.sh
      - type: bind
        source: ${PWD}/nginx/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ${PWD}/static
        target: /usr/share/nginx/html
    entrypoint: /docker-entrypoint.sh
